spring.application.name: catalog-service

spring:
  cassandra:
    keyspace-name: catalog
    port: 9042
    contact-points: cassandra-node-0
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-server:3306/my_db?useSSL=false&useTimezone=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: user
  data:
    redis:
      host: myredis
      port: 6379
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers:
      - kafka1:9092
      - kafka2:9092
      - kafka3:9092
    consumer:
      group-id: testgroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer